services:
  - type: web
    name: cpt-website-bca
    env: static
    buildCommand: npm run build
    staticPublishPath: ./out
    routes:
      - type: rewrite
        source: /*
        destination: /index.html